// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/goodguy-project/goodguy-desktop/dal/model"
)

func newFollower(db *gorm.DB, opts ...gen.DOOption) follower {
	_follower := follower{}

	_follower.followerDo.UseDB(db, opts...)
	_follower.followerDo.UseModel(&model.Follower{})

	tableName := _follower.followerDo.TableName()
	_follower.ALL = field.NewAsterisk(tableName)
	_follower.ID = field.NewUint(tableName, "id")
	_follower.CreatedAt = field.NewTime(tableName, "created_at")
	_follower.UpdatedAt = field.NewTime(tableName, "updated_at")
	_follower.DeletedAt = field.NewField(tableName, "deleted_at")
	_follower.Name = field.NewString(tableName, "name")
	_follower.CodeforcesId = field.NewString(tableName, "codeforces_id")
	_follower.AtcoderId = field.NewString(tableName, "atcoder_id")
	_follower.NowcoderId = field.NewString(tableName, "nowcoder_id")
	_follower.LuoguId = field.NewString(tableName, "luogu_id")
	_follower.VjudgeId = field.NewString(tableName, "vjudge_id")
	_follower.LeetcodeId = field.NewString(tableName, "leetcode_id")

	_follower.fillFieldMap()

	return _follower
}

type follower struct {
	followerDo followerDo

	ALL          field.Asterisk
	ID           field.Uint
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field
	Name         field.String
	CodeforcesId field.String
	AtcoderId    field.String
	NowcoderId   field.String
	LuoguId      field.String
	VjudgeId     field.String
	LeetcodeId   field.String

	fieldMap map[string]field.Expr
}

func (f follower) Table(newTableName string) *follower {
	f.followerDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f follower) As(alias string) *follower {
	f.followerDo.DO = *(f.followerDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *follower) updateTableName(table string) *follower {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewUint(table, "id")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.DeletedAt = field.NewField(table, "deleted_at")
	f.Name = field.NewString(table, "name")
	f.CodeforcesId = field.NewString(table, "codeforces_id")
	f.AtcoderId = field.NewString(table, "atcoder_id")
	f.NowcoderId = field.NewString(table, "nowcoder_id")
	f.LuoguId = field.NewString(table, "luogu_id")
	f.VjudgeId = field.NewString(table, "vjudge_id")
	f.LeetcodeId = field.NewString(table, "leetcode_id")

	f.fillFieldMap()

	return f
}

func (f *follower) WithContext(ctx context.Context) *followerDo { return f.followerDo.WithContext(ctx) }

func (f follower) TableName() string { return f.followerDo.TableName() }

func (f follower) Alias() string { return f.followerDo.Alias() }

func (f *follower) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *follower) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 11)
	f.fieldMap["id"] = f.ID
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["deleted_at"] = f.DeletedAt
	f.fieldMap["name"] = f.Name
	f.fieldMap["codeforces_id"] = f.CodeforcesId
	f.fieldMap["atcoder_id"] = f.AtcoderId
	f.fieldMap["nowcoder_id"] = f.NowcoderId
	f.fieldMap["luogu_id"] = f.LuoguId
	f.fieldMap["vjudge_id"] = f.VjudgeId
	f.fieldMap["leetcode_id"] = f.LeetcodeId
}

func (f follower) clone(db *gorm.DB) follower {
	f.followerDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f follower) replaceDB(db *gorm.DB) follower {
	f.followerDo.ReplaceDB(db)
	return f
}

type followerDo struct{ gen.DO }

func (f followerDo) Debug() *followerDo {
	return f.withDO(f.DO.Debug())
}

func (f followerDo) WithContext(ctx context.Context) *followerDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f followerDo) ReadDB() *followerDo {
	return f.Clauses(dbresolver.Read)
}

func (f followerDo) WriteDB() *followerDo {
	return f.Clauses(dbresolver.Write)
}

func (f followerDo) Session(config *gorm.Session) *followerDo {
	return f.withDO(f.DO.Session(config))
}

func (f followerDo) Clauses(conds ...clause.Expression) *followerDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f followerDo) Returning(value interface{}, columns ...string) *followerDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f followerDo) Not(conds ...gen.Condition) *followerDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f followerDo) Or(conds ...gen.Condition) *followerDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f followerDo) Select(conds ...field.Expr) *followerDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f followerDo) Where(conds ...gen.Condition) *followerDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f followerDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *followerDo {
	return f.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (f followerDo) Order(conds ...field.Expr) *followerDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f followerDo) Distinct(cols ...field.Expr) *followerDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f followerDo) Omit(cols ...field.Expr) *followerDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f followerDo) Join(table schema.Tabler, on ...field.Expr) *followerDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f followerDo) LeftJoin(table schema.Tabler, on ...field.Expr) *followerDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f followerDo) RightJoin(table schema.Tabler, on ...field.Expr) *followerDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f followerDo) Group(cols ...field.Expr) *followerDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f followerDo) Having(conds ...gen.Condition) *followerDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f followerDo) Limit(limit int) *followerDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f followerDo) Offset(offset int) *followerDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f followerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *followerDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f followerDo) Unscoped() *followerDo {
	return f.withDO(f.DO.Unscoped())
}

func (f followerDo) Create(values ...*model.Follower) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f followerDo) CreateInBatches(values []*model.Follower, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f followerDo) Save(values ...*model.Follower) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f followerDo) First() (*model.Follower, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Follower), nil
	}
}

func (f followerDo) Take() (*model.Follower, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Follower), nil
	}
}

func (f followerDo) Last() (*model.Follower, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Follower), nil
	}
}

func (f followerDo) Find() ([]*model.Follower, error) {
	result, err := f.DO.Find()
	return result.([]*model.Follower), err
}

func (f followerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Follower, err error) {
	buf := make([]*model.Follower, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f followerDo) FindInBatches(result *[]*model.Follower, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f followerDo) Attrs(attrs ...field.AssignExpr) *followerDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f followerDo) Assign(attrs ...field.AssignExpr) *followerDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f followerDo) Joins(fields ...field.RelationField) *followerDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f followerDo) Preload(fields ...field.RelationField) *followerDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f followerDo) FirstOrInit() (*model.Follower, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Follower), nil
	}
}

func (f followerDo) FirstOrCreate() (*model.Follower, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Follower), nil
	}
}

func (f followerDo) FindByPage(offset int, limit int) (result []*model.Follower, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f followerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f followerDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f followerDo) Delete(models ...*model.Follower) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *followerDo) withDO(do gen.Dao) *followerDo {
	f.DO = *do.(*gen.DO)
	return f
}
