// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanCrawlCache() {
  return window['go']['main']['App']['CleanCrawlCache']();
}

export function DeleteFollower(arg1) {
  return window['go']['main']['App']['DeleteFollower'](arg1);
}

export function GetContestRecord(arg1) {
  return window['go']['main']['App']['GetContestRecord'](arg1);
}

export function GetCrawlSetting() {
  return window['go']['main']['App']['GetCrawlSetting']();
}

export function GetDailyQuestion(arg1) {
  return window['go']['main']['App']['GetDailyQuestion'](arg1);
}

export function GetPageInfo() {
  return window['go']['main']['App']['GetPageInfo']();
}

export function GetRecentContest(arg1) {
  return window['go']['main']['App']['GetRecentContest'](arg1);
}

export function GetSubmitRecord(arg1) {
  return window['go']['main']['App']['GetSubmitRecord'](arg1);
}

export function LoadFollower(arg1) {
  return window['go']['main']['App']['LoadFollower'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveFollower(arg1) {
  return window['go']['main']['App']['SaveFollower'](arg1);
}

export function SearchFollower(arg1) {
  return window['go']['main']['App']['SearchFollower'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetPageInfo(arg1) {
  return window['go']['main']['App']['SetPageInfo'](arg1);
}

export function UpdateCrawlSetting(arg1) {
  return window['go']['main']['App']['UpdateCrawlSetting'](arg1);
}
