// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proto} from '../models';
import {core} from '../models';
import {main} from '../models';
import {model} from '../models';

export function CleanCrawlCache():Promise<void>;

export function DeleteFollower(arg1:Array<number>):Promise<void>;

export function GetContestRecord(arg1:proto.GetContestRecordRequest):Promise<proto.GetContestRecordResponse>;

export function GetCrawlSetting():Promise<core.CrawlSetting>;

export function GetDailyQuestion(arg1:proto.GetDailyQuestionRequest):Promise<proto.GetDailyQuestionResponse>;

export function GetPageInfo():Promise<main.PageInfo>;

export function GetRecentContest(arg1:proto.GetRecentContestRequest):Promise<proto.GetRecentContestResponse>;

export function GetSubmitRecord(arg1:proto.GetSubmitRecordRequest):Promise<proto.GetSubmitRecordResponse>;

export function LoadFollower(arg1:string):Promise<void>;

export function SaveFile(arg1:string):Promise<string>;

export function SaveFollower(arg1:model.Follower):Promise<void>;

export function SearchFollower(arg1:core.SearchFollowerRequest):Promise<Array<model.Follower>>;

export function SelectFile():Promise<string>;

export function SetPageInfo(arg1:main.PageInfo):Promise<void>;

export function UpdateCrawlSetting(arg1:core.CrawlSetting):Promise<void>;
